WIP: Improve Handler behavior names
viceroypenguin/Immediate.Handlers pull request #18
Opened 2024-01-13 22:28 UTC by Head0nF1re

- Add snapshot tests for identifier names.

- Add computed property from Behavior.RegistrationType in order to generate a valid identifier name.

- Change Handler scriban template (**failing**)

2024-01-14 13:56 UTC, viceroypenguin requested changes
Two comments (and a way to fix them):
* Adding a mutable field to the `Behavior` type means that it is no longer properly equatable, which means it is no longer correctly cacheable. 
* The rendered names are way too long.

Instead of adding something to the `Behavior` type, we can do something slightly different.

1. Update the `Behavior` type to receive the simple name of the type, which can be obtained in TransformBehaviors by calling `.Name` of the originaldefinition. 
2. Update transform handlers code in the entrypoint file to use something like:
```cs
var names = new Dictionary<string, int>()
{
  ["HandleBehavior"] = 1,
};

string GetSuffix(string name)
{
  if (!names.TryGetValue(name, out var cnt))
    cnt = 0;
  names[name] = cnt + 1;
  return cnt == 0 ? "" : $"{cnt}";
}

var renderBehaviors = behaviors
  .Select(b => new
  {
    b.NonGenericTypeName,
    VariableName = b.Name + GetSuffix(b.Name),
  })
  .ToList();
```

3. Then pass the new `renderBehaviors` to the template instead, and it can get the variable from the `{{ b.behavior_name }}` value.

2024-01-14 18:54 UTC, Head0nF1re commented
@viceroypenguin 

> The rendered names are way too long.

Yeah, thought it would be more readable in case a user wants to peek into the generated `Handler`.

With **fully qualified name**:
```csharp
_HandleBehavior = HandleBehavior;
_Dummy_LoggingBehavior = Dummy_LoggingBehavior;
_YetAnotherDummy_OtherBehavior = YetAnotherDummy_OtherBehavior;
_Dummy_SecondLoggingBehavior = Dummy_SecondLoggingBehavior;
_YetAnotherDummy_LoggingBehavior = YetAnotherDummy_LoggingBehavior;
_YetAnotherDummy_SecondLoggingBehavior = YetAnotherDummy_SecondLoggingBehavior;

_YetAnotherDummy_SecondLoggingBehavior.SetInnerHandler(_HandleBehavior);
_YetAnotherDummy_LoggingBehavior.SetInnerHandler(_YetAnotherDummy_SecondLoggingBehavior);
_Dummy_SecondLoggingBehavior.SetInnerHandler(_YetAnotherDummy_LoggingBehavior);
_YetAnotherDummy_OtherBehavior.SetInnerHandler(_Dummy_SecondLoggingBehavior);
_Dummy_LoggingBehavior.SetInnerHandler(_YetAnotherDummy_OtherBehavior);
``` 

With **class name**:
```csharp
_HandleBehavior = HandleBehavior;
_LoggingBehavior1 = LoggingBehavior1;
_OtherBehavior = OtherBehavior;
_SecondLoggingBehavior1 = SecondLoggingBehavior1;
_LoggingBehavior2 = LoggingBehavior2;
_SecondLoggingBehavior2 = SecondLoggingBehavior2;

_SecondLoggingBehavior2.SetInnerHandler(_HandleBehavior);
LoggingBehavior2.SetInnerHandler(_SecondLoggingBehavior2);
SecondLoggingBehavior1.SetInnerHandler(_LoggingBehavior2);
OtherBehavior.SetInnerHandler(_SecondLoggingBehavior1);
LoggingBehavior1.SetInnerHandler(_OtherBehavior);
``` 

This would be more meaningful in the case where the same `Type.Name` would be declared in different namespaces like we talked on Discord, since the type information isn't displayed on hover you would need to scroll up and down (see the var types) to better visualize what's going on. 
But yeah, since that will rarely happen, guess that's not a problem. Will update then.


---

Regarding the caching, you mean in the [Incremental Generator](https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md#caching)? Help me visualize please, doesn't the generator run `TransformBehaviors` each time since the predicate only checks if the node is `CompilationUnitSyntax`? Or, would the problem be in later stages of the pipeline?

2024-01-15 03:26 UTC, viceroypenguin requested changes

2024-01-15 03:26 UTC, viceroypenguin commented on src/Immediate.Handlers.Generators/ImmediateHandlers/ImmediateHandlersGenerator_TransformBehaviors.cs
> +					Name = originalDefinition.Name
add a comma here

2024-01-15 03:26 UTC, viceroypenguin commented on src/Immediate.Handlers.Generators/ImmediateHandlers/ImmediateHandlersGenerator_TransformHandler.cs
> -				is { } rma
unexpected whitespace changes in this file

2024-01-15 03:26 UTC, viceroypenguin commented on src/Immediate.Handlers.Generators/ImmediateHandlers/ImmediateHandlersGenerator_Entrypoint.cs
> +		var renderBehaviors = pipelineBehaviors.Select(b =>
for readability, change to:
```cs
var renderBehaviors = pipelineBehaviors
  .Select(..
  )
  .ToList();
```

2024-01-15 03:50 UTC, merged